name: Docker image builds
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  disk-cache:
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "disk-cache"
      username: "ajayyy"
      folder: "."
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}